version: "3"

services:
  mirage:
    image: codingminutes/mirage
    env_file:
      - .env
    ports:
      - "8765:8765"
    build: .
    depends_on:
      - postgres
  postgres:
     image: postgres:12.7
     volumes:
      - ./postgres-data:/var/lib/postgresql/data
     env_file:
      - .env