# Generated by Django 3.2.6 on 2021-08-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("longUrl", models.URLField(max_length=256)),
                ("author", models.UUIDField()),
            ],
        ),
    ]
