# Generated by Django 3.2.6 on 2021-09-12 07:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField()),
                ('description', models.CharField(max_length=300)),
                ('link', models.OneToOneField(on_delete=models.SET(api.models.get_deleted_link), to='api.links')),
            ],
        ),
    ]
